# Generated by Django 2.2.7 on 2021-01-27 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='')),
                ('is_online', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(blank=True)),
                ('posts', models.IntegerField(default=0)),
                ('friends', models.IntegerField(default=0)),
                ('subscribers', models.IntegerField(default=0)),
                ('subscriptions', models.IntegerField(default=0)),
                ('access_messaging', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('access_add_friends', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('access_post', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('access_about', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('access_albums', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('access_images', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('access_stats', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('access_profile', models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friends', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('main_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='user_profile.Profile')),
                ('related_object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UsersRelation')),
                ('secondary_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user_profile.Profile')),
            ],
        ),
    ]
