# Generated by Django 2.2.7 on 2021-04-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_add_friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='access_posts',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_about',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_albums',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_images',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_messaging',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_stats',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
    ]
