# Generated by Django 2.2.7 on 2020-03-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200331_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_online',
        ),
    ]
