# Generated by Django 2.2.7 on 2020-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20200407_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_posts',
            field=models.IntegerField(default=0),
        ),
    ]
