# Generated by Django 2.2.7 on 2020-10-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20200903_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_messages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_subscribers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_subscriptions',
        ),
        migrations.AddField(
            model_name='profile',
            name='access_add_friends',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_albums',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_messaging',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_post',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_stats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_about',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_images',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_profile',
            field=models.IntegerField(default=1),
        ),
    ]
