# Generated by Django 2.2.7 on 2020-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20201016_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_about',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_add_friends',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_albums',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_images',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_messaging',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_post',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_profile',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_stats',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
    ]
