# Generated by Django 2.2.7 on 2021-01-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_usersrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrelation',
            name='related_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UsersRelation'),
        ),
    ]
