# Generated by Django 2.2.7 on 2020-04-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0004_auto_20200331_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friends', models.BooleanField(default=False)),
                ('is_one_subscribed_two', models.BooleanField(default=False)),
                ('is_two_subscribed_one', models.BooleanField(default=False)),
                ('is_one_block_two', models.BooleanField(default=False)),
                ('is_two_block_one', models.BooleanField(default=False)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='user_profile.Profile')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user_profile.Profile')),
            ],
        ),
    ]
