# Generated by Django 2.2.7 on 2020-04-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relations',
            old_name='is_one_block_two',
            new_name='is_block',
        ),
        migrations.RenameField(
            model_name='relations',
            old_name='is_one_subscribed_two',
            new_name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='relations',
            name='is_two_block_one',
        ),
        migrations.RemoveField(
            model_name='relations',
            name='is_two_subscribed_one',
        ),
    ]
