# Generated by Django 2.2.7 on 2020-04-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_auto_20200403_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='user_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='user_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='relations',
            name='user_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user_profile.Profile'),
        ),
    ]
