# Generated by Django 2.2.7 on 2020-08-28 17:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message_time',
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='connection2chat',
            name='recipient',
            field=models.IntegerField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
