# Generated by Django 3.2 on 2021-04-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionToChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'simple user'), (2, 'administrator'), (3, 'creator')], default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_seen',
            new_name='is_ancillary',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_message_time',
        ),
        migrations.AddField(
            model_name='chat',
            name='add_new_users',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='add_remove_admins',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=3),
        ),
        migrations.AddField(
            model_name='chat',
            name='change_chat_image',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='change_chat_name',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='del_messages',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='remove_users',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='see_admins',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='send_messages',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Admins'), (3, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PrivateChatConnection',
            fields=[
                ('connectiontochat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.connectiontochat')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('message.connectiontochat',),
        ),
        migrations.CreateModel(
            name='PublicChatConnection',
            fields=[
                ('connectiontochat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.connectiontochat')),
                ('chat_num', models.IntegerField(default=1, null=True)),
            ],
            bases=('message.connectiontochat',),
        ),
        migrations.DeleteModel(
            name='Connection2Chat',
        ),
        migrations.AddField(
            model_name='connectiontochat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.chat'),
        ),
        migrations.AddField(
            model_name='connectiontochat',
            name='last_seen_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_seen_message', to='message.message'),
        ),
        migrations.AddField(
            model_name='connectiontochat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='connections', through='message.ConnectionToChat', to=settings.AUTH_USER_MODEL),
        ),
    ]
