# Generated by Django 2.2.7 on 2020-08-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200828_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection2chat',
            name='chat_num',
            field=models.IntegerField(null=True),
        ),
    ]
