# Generated by Django 2.2.7 on 2020-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_connection2chat_chat_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection2chat',
            name='role',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_amount',
            field=models.IntegerField(default=0),
        ),
    ]
