# Generated by Django 2.2.7 on 2020-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20201020_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='add_new_users',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='add_remove_admins',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='chat',
            name='change_chat_image',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='change_chat_name',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='del_messages',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='remove_users',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='chat',
            name='see_admins',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='see_messages',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='send_messages',
            field=models.IntegerField(default=1),
        ),
    ]
