# Generated by Django 2.2.7 on 2020-10-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20201020_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ancillary',
            field=models.BooleanField(default=False),
        ),
    ]
