# Generated by Django 2.2.7 on 2020-11-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_message_is_ancillary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection2chat',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
