# Generated by Django 2.2.7 on 2020-11-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20201108_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
