# Generated by Django 2.2.7 on 2020-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_message_is_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='add_new_users',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='chat',
            name='add_remove_admins',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=3),
        ),
        migrations.AlterField(
            model_name='chat',
            name='change_chat_image',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=2),
        ),
        migrations.AlterField(
            model_name='chat',
            name='change_chat_name',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=2),
        ),
        migrations.AlterField(
            model_name='chat',
            name='del_messages',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=2),
        ),
        migrations.AlterField(
            model_name='chat',
            name='remove_users',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=2),
        ),
        migrations.AlterField(
            model_name='chat',
            name='see_admins',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='chat',
            name='see_messages',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AlterField(
            model_name='chat',
            name='send_messages',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
    ]
