# Generated by Django 2.2.7 on 2021-04-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_auto_20201111_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection2chat',
            name='role',
            field=models.IntegerField(choices=[(1, 'simple user'), (2, 'administrator'), (3, 'creator')], default=1),
        ),
    ]
