# Generated by Django 3.2 on 2021-04-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exist', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_publication']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='like_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='repost_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reposts_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='see_author_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='see_comments_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='see_post_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='see_statistic_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('likes_amount', models.IntegerField(default=0)),
                ('is_changed', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Tag'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('baselike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.baselike')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            bases=('posts.baselike',),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('baselike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.baselike')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
            ],
            bases=('posts.baselike',),
        ),
    ]
