# Generated by Django 2.2.7 on 2020-09-18 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20200830_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='exist',
            field=models.BooleanField(default=True),
        ),
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exist', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='posts.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
