# Generated by Django 2.2.7 on 2020-09-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200922_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='exist',
            field=models.BooleanField(default=False),
        ),
    ]
