# Generated by Django 2.2.7 on 2020-10-01 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200922_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Like')),
            ],
            bases=('posts.like', django.views.generic.base.View),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
