# Generated by Django 2.2.7 on 2020-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201001_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
