# Generated by Django 2.2.7 on 2020-11-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201005_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
