# Generated by Django 2.2.7 on 2020-11-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
