# Generated by Django 2.2.7 on 2020-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_permission',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='like_permission',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='repost_permission',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='see_author_permission',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='see_post_permission',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='see_statistic_permission',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
    ]
