# Generated by Django 2.2.7 on 2020-11-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201111_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='see_comments_permission',
            field=models.IntegerField(choices=[(1, 'All Users'), (2, 'Only Subscribers'), (3, 'Only Friends'), (4, 'Nobody')], default=1),
        ),
    ]
