# Generated by Django 2.2.7 on 2021-04-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_see_comments_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='repost_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='see_author_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='see_comments_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='see_post_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='see_statistic_permission',
            field=models.IntegerField(choices=[(0, 'All Users'), (2, 'Only Subscribers'), (4, 'Only Friends'), (5, 'Nobody')], default=0),
        ),
    ]
